tasks:
  - init: yarn install
    before: npm install t3k --global
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: false
image:
  file: .gitpod.Dockerfile
